### ISSUE TITLE
[Modern Search] Incorrect search query if use "Send query to a new page"

### ISSUE THREAD

**Issue by vui211** [SharePoint/sp-dev-solutions#93]
Hi @wobba , @FranckyC 
#### Category
- [ ] Question
- [ x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Search result should process query from Search Box and Url string correctly.

#### Observed Behavior
I configured Search Box web part
![image](https://user-images.githubusercontent.com/23225932/55039606-b3df2c80-5089-11e9-88da-272125dd42c2.png)

It works if search term is single word like "fresh" but if I use "fresh produce" Search result web part on targeted page runs query for "fresh%20produce" and return incorrect results. So it doesn't decode query fragment "#" correctly.
![image](https://user-images.githubusercontent.com/23225932/55039852-cd34a880-508a-11e9-87dd-0024999df2b1.png)

We use 3.0.0.4 version

Thanks
#### Steps to Reproduce
Above

**Comment by FranckyC** [comment]
@vui211 should be fixed now.

**Comment by axelgz** [comment]
I'm still seeing the issue after a fresh deployment.
homepage:
![image](https://user-images.githubusercontent.com/48997385/55095624-d7f13c80-508e-11e9-83de-3cf32eacd9bc.png)

Results page:
![image](https://user-images.githubusercontent.com/48997385/55096159-bd6b9300-508f-11e9-8001-2e14ec251353.png)


After hitting Enter in Search Box in Result page it show correct results:
![image](https://user-images.githubusercontent.com/48997385/55096070-990fb680-508f-11e9-9937-930ddfd2ada8.png)

**Comment by FranckyC** [comment]
@axelgz Do you use the latest version? we've pushed a couple of minutes ago a new one.

**Comment by YannickRe** [comment]
@axelgz There is something strange going on in your installation. I tested it on my side, and it works without problems (after the fix from @FranckyC).
![Results](https://user-images.githubusercontent.com/9973962/55097998-451bc680-50bd-11e9-95eb-7a8b33656f1a.PNG)

Now, something I've noticed that might be related: if you have no results, it shows the empty pagination control. This is something I fixed in v3.0.2 and since you run 3.0.4, there seems to be an upgrade issue.
It is supposed to be empty, like this:
![NoResults](https://user-images.githubusercontent.com/9973962/55098075-709eb100-50bd-11e9-9266-be45167d41c0.PNG)

Can you try to pull the latest master branch, build a package, uninstall the app from you site collection, then uninstall from your app catalog and then reinstall the new package (first app catalog, then site collection)? Just making sure we actually are running the latest version (which is now 3.0.5).

**Comment by axelgz** [comment]
Hi,

I downloaded and re-deployed again. It is working as expected. 

Thank you
